package de.sormuras.stash.compiler;

enum Tag {
  METHOD_IS_BASE,
  METHOD_IS_CHAINABLE,
  METHOD_IS_VOLATILE,
  METHOD_IS_DIRECT,
  PARAMETER_IS_ENUM,
  PARAMETER_IS_STASHABLE,
  PARAMETER_IS_TIME
}
