language: java
jdk: oraclejdk8

notifications:
  email:
    on_success: always
    on_failure: always

install: java -version

script:
  - ./gradlew -version
  - ./gradlew --refresh-dependencies clean build
