
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Set up Java'
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: 'Build with Bach'
        uses: sormuras/bach-build@v1
        with:
          bach-arguments: --project-version 1-ea+${{ github.sha }} build
      - name: 'Upload artifact ${{ github.event.repository.name }}-build-${{ github.sha }}'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ github.sha }}
          path: |
            .bach/workspace/logbook.md
            .bach/workspace/modules
            .bach/workspace/reports
      - name: 'Release Stash 1-ea+${{ github.sha }}'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: 1-ea
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          title: "Stash 1-ea+${{ github.sha }}"
          files: |
            .bach/workspace/modules/*.jar
